### ISSUE TITLE
JS build with unused django app

### ISSUE THREAD

**Issue by Supermanu** [protibimbok/django-vite-plugin#65]
Hi,
Currently in my project, we have multiple django applications with different entry points. In each application we have a folder `static/app/js/…`. In order to find the entry points in the vite config file we use `globSync("*/static/*/js/*.js")` which works almost perfectly. In deed, if we remove the app in django with the `INSTALLED_APPS` variable but not the files, vite cannot build. Like this (student_absence_teacher being the django app deactivated) :
```
x Build failed in 40ms
error during build:
Could not resolve entry module "student_absence_teacher/js/student_absence_teacher.js".
    at getRollupError (file:///home/manuel/Developpement/Python/happyschool/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at error (file:///home/manuel/Developpement/Python/happyschool/node_modules/rollup/dist/es/shared/parseAst.js:392:42)
    at ModuleLoader.loadEntryModule (file:///home/manuel/Developpement/Python/happyschool/node_modules/rollup/dist/es/shared/node-entry.js:19123:20)
    at async Promise.all (index 0)
```
Is there a way, without modifying the `vite.config.js` file, to build nevertheless?

**Comment by protibimbok** [comment]
Do you mean you want to build the assets from APPS that are not installed?

**Comment by Supermanu** [comment]
Yes, that would be one way to solve my case as I often activate/deactivate django apps. Another way would be to have in the `vite.config.js` access to the activated django apps, so I can exclude them from the build.

**Comment by Supermanu** [comment]
To answer myself, I now use the django-vite-plugin command to be aware of the django installed apps in the `vite.config.js` file and filter out unneeded path. Like this:
```
import { spawnSync } from "child_process";

const py = spawnSync("python", ["manage.py", "django_vite_plugin", "--action", "config"]);
const installedApps = Object.keys(JSON.parse(py.stdout.toString()).INSTALLED_APPS);
```
Activating/deactivating a django app still needs to rebuild the `js` side, but I can automate that part so I'm comfortable with this solution.
